unit MD.Opacitys;

interface

uses
  MD.ColorPalette;

const

  // Text opacity
  DARKTEXT_PRIMARY_OPACITY = 0.87;
  DARKTEXT_SECONDARY_OPACITY = 0.54;
  DARKTEXT_DISABLED_OPACITY = 0.38;
  DARKTEXT_HINT_OPACITY = 0.38;
  DARKTEXT_ICONS_OPACITY = 0.38;
  DARKTEXT_DIVIDERS_OPACITY = 0.12;

  WHITETEXT_PRIMARY_OPACITY = 1;
  WHITETEXT_SECONDARY_OPACITY = 0.70;
  WHITETEXT_DISABLED_OPACITY = 0.50;
  WHITETEXT_HINT_OPACITY = 0.50;
  WHITETEXT_ICONS_OPACITY = 0.50;
  WHITETEXT_DIVIDERS_OPACITY = 0.12;

  // Icons, dividers, and other elements
  DARKELEMENT_ACTIVE_OPACITY = 0.54;
  DARKELEMENT_INACTIVE_OPACITY = 0.38;

  WHITEELEMENT_ACTIVE_OPACITY = 1;
  WHITEELEMENT_INACTIVE_OPACITY = 0.50;



implementation

end.
